name: example
description: A project used to demo the freezify
version: 0.0.1
author: azihsoyn <azihsoyn@gmail.com>
homepage: https://github.com/azihsoyn/freezify

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezify_annotation:
    path: ../freezify_annotation/
  freezed_annotation:

dev_dependencies:
  build_runner: ^1.0.0
  freezify:
    path: ../freezify/
  freezed: